[project]
name = "vng_api"
version = "2026.0.0a1"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.14.3",
    "orjson>=2.01",
    "mashumaro>=3.22"
]
authors = [{name = "Lena During"}]
description = "An async API client for the game \"Von Neumann Game\" (https://neumann-probe.net)"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
